### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by hangocdinhnew** [HangocdinhNewOrganization/MyProject#1]
Linking Errors.

**Comment by Harry262530** [comment]
hello @hangocdinhnew is there any help needed where I can contribute
Please ping me if required

**Comment by hangocdinhnew** [comment]
And You can contribute this project if you want but 
Note: this is for m1 mac only, you need to modified it vcpkg and you need to install package too.

**Comment by hangocdinhnew** [comment]
Solved! Closing the Issue
